spring.application.name=sidTask
# MySQL DB settings (update for your DB)
server.port=8081

db.url=jdbc:mysql://localhost:3306/sidtaskdb
db.user=root
db.password=sam123

# Mail settings (example for Gmail SMTP; update if using another SMTP)
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.username=samvjaathish@gmail.com
mail.password=impf txja dxpx udjy
mail.from=samvjaathish@gmail.com
